@baseUrl = http://localhost:3003

# Login
POST {{baseUrl}}/api/blogs
Content-Type: application/json

{
    "title": "El Psy Congroo",
    "author": "Okarin",
    "url": "Blank For Now",
    "likes": 9
}
###

# Get User
GET {{baseUrl}}/api/blogs