@baseUrl = http://localhost:3003

// Create new user
POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "username": "Hyouin Kyouma",
    "name": "Okabe Rintaro",
    "password": "El Psy Congroo"
}
###

// Invalid User creation
POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "username": "Hyo",
    "name": "Okabe Rintaro",
    "password": "El"
}