@baseUrl = http://localhost:3003

// Create new user
POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "username": "Hyouin Kyouma",
    "name": "Okabe Rintaro",
    "password": "El Psy Congroo"
}
###

// Invalid User creation
POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "username": "Hy",
    "name": "Okabe Rintaro",
    "password": "Elsdw"
}

### Create a new user
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "john_doe",
    "name": "John Doe",
    "password": "secure123"
}

### Create a new blog for that user
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Old-School Programming",
  "author": "John Doe",
  "url": "https://johnsblog.com/blogs/old-school-programming",
  "likes": 62,
  "user": "6878ee55485aeb3b3046acbf"
}